const CASES=window.T5_CASES||[];
const canvas=document.getElementById('chart'),ctx=canvas.getContext('2d');
const caseList=document.getElementById('caseList');
let current=0,tf='M5',dragA=null,dragB=null,submitted=false,revealed=false,futureHours=0;
const STORE='t5_liquidity_real20_v1';
let state={};
try{state=JSON.parse(localStorage.getItem(STORE)||'{}')}catch(_){state={}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function C(){return CASES[current]}
function D(){return C().data[tf]}
function futureCountForHours(d,hours){if(!hours)return d.visibleCount;const mins={M5:5,M15:15,H1:60}[tf];return Math.min(d.bars.length,d.visibleCount+Math.ceil(hours*60/mins))}
function buildList(){caseList.innerHTML='';CASES.forEach((c,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');if(i===current)b.classList.add('current');if(state[c.id])b.classList.add('done');b.onclick=()=>loadCase(i);caseList.appendChild(b)})}
function completed(){return CASES.filter(c=>state[c.id]&&typeof state[c.id].score==='number')}
function stats(){const done=completed(),vals=done.map(c=>state[c.id].score);const avg=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):null;document.getElementById('progressText').textContent=`${done.length} / ${CASES.length}`;document.getElementById('progressFill').style.width=`${CASES.length?done.length/CASES.length*100:0}%`;document.getElementById('avgScore').textContent=avg===null?'—':avg+'%';document.getElementById('exactCount').textContent=vals.length?vals.filter(x=>x===100).length:'—';document.getElementById('doneCount').textContent=done.length;document.getElementById('reportBtn').disabled=done.length<5}
function loadCase(i){current=i;tf='M5';dragA=dragB=null;submitted=false;revealed=false;futureHours=0;document.querySelectorAll('.tf-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tf==='M5'));document.getElementById('result').classList.add('hidden');document.getElementById('report').classList.add('hidden');document.getElementById('futureControls').classList.add('hidden');document.getElementById('outcomeBox').classList.add('hidden');document.getElementById('submitBtn').disabled=false;document.getElementById('revealBtn').disabled=true;document.getElementById('revealBtn').textContent='查看后续12小时';document.getElementById('nextBtn').disabled=true;document.getElementById('caseMeta').textContent=`Scenario #${String(C().id).padStart(2,'0')} · ${C().symbol} · ${C().decisionTime} · ${C().serverTZ}`;document.getElementById('question').textContent=C().question;document.getElementById('cornerText').textContent='未来行情已隐藏';buildList();resize()}
function resize(){const dpr=window.devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
window.addEventListener('resize',resize);
function bounds(){const d=D(),n=revealed?futureCountForHours(d,futureHours):d.visibleCount,arr=d.bars.slice(0,n);let lo=Math.min(...arr.map(x=>x[2])),hi=Math.max(...arr.map(x=>x[1]));const pad=Math.max((hi-lo)*.07,C().atr*.7);return{lo:lo-pad,hi:hi+pad,n}}
function py(price,b,h){return 24+(b.hi-price)/(b.hi-b.lo)*(h-52)}
function yp(y,b,h){return b.hi-((y-24)/(h-52))*(b.hi-b.lo)}
function draw(){if(!CASES.length)return;const r=canvas.getBoundingClientRect(),w=r.width,h=r.height,d=D(),b=bounds(),arr=d.bars.slice(0,b.n);ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.font='11px -apple-system,BlinkMacSystemFont,sans-serif';for(let i=0;i<6;i++){const y=24+i*(h-52)/5;ctx.strokeStyle='#eceef2';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(w-58,y);ctx.stroke();const p=b.hi-i*(b.hi-b.lo)/5;ctx.fillStyle='#7b818c';ctx.fillText(p.toFixed(2),w-53,y+4)}const x0=48,plotW=w-112,gap=plotW/Math.max(b.n,1),bw=Math.max(2.2,gap*.58);arr.forEach((c,i)=>{const x=x0+i*gap+gap/2,yo=py(c[0],b,h),yh=py(c[1],b,h),yl=py(c[2],b,h),yc=py(c[3],b,h),up=c[3]>=c[0];ctx.strokeStyle=up?'#242931':'#6f7682';ctx.fillStyle=up?'#fff':'#2c3139';ctx.beginPath();ctx.moveTo(x,yh);ctx.lineTo(x,yl);ctx.stroke();const top=Math.min(yo,yc),bh=Math.max(1,Math.abs(yc-yo));ctx.fillRect(x-bw/2,top,bw,bh);ctx.strokeRect(x-bw/2,top,bw,bh)});const decisionX=x0+d.visibleCount*gap;if(revealed){ctx.fillStyle='rgba(80,86,96,.035)';ctx.fillRect(decisionX,18,Math.max(0,w-58-decisionX),h-45)}ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='#8f96a2';ctx.beginPath();ctx.moveTo(decisionX,18);ctx.lineTo(decisionX,h-27);ctx.stroke();ctx.restore();ctx.fillStyle='#777e89';ctx.fillText('决策时刻',Math.max(50,decisionX-24),h-10);if(dragA&&dragB){const y=Math.min(dragA.y,dragB.y),rh=Math.max(2,Math.abs(dragB.y-dragA.y)),x=48,rw=w-112;ctx.fillStyle='rgba(28,32,39,.10)';ctx.strokeStyle='#1f242c';ctx.lineWidth=1.6;ctx.fillRect(x,y,rw,rh);ctx.strokeRect(x,y,rw,rh);const pTop=yp(y,b,h),pBottom=yp(y+rh,b,h),lo=Math.min(pTop,pBottom),hi=Math.max(pTop,pBottom),label=`已选择 ${lo.toFixed(2)} – ${hi.toFixed(2)}`;ctx.font='12px sans-serif';const tw=ctx.measureText(label).width+16,ly=Math.max(20,Math.min(h-32,y-8));ctx.fillStyle='rgba(27,30,36,.94)';ctx.fillRect(54,ly-16,tw,22);ctx.fillStyle='#fff';ctx.fillText(label,62,ly)}if(submitted){const y1=py(C().answer.high,b,h),y2=py(C().answer.low,b,h);ctx.fillStyle='rgba(60,66,76,.08)';ctx.strokeStyle='#4d5460';ctx.setLineDash([4,4]);ctx.fillRect(48,y1,w-112,y2-y1);ctx.strokeRect(48,y1,w-112,y2-y1);ctx.setLineDash([]);ctx.fillStyle='#555c68';ctx.fillText('T5规则区域',53,Math.max(13,y1-5))}}
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
let selecting=false;canvas.style.touchAction='none';
canvas.addEventListener('pointerdown',e=>{if(submitted)return;selecting=true;canvas.setPointerCapture?.(e.pointerId);const p=pos(e);dragA={x:48,y:p.y};dragB={x:canvas.getBoundingClientRect().width-64,y:p.y};e.preventDefault();draw()});
canvas.addEventListener('pointermove',e=>{if(!selecting||submitted)return;const p=pos(e);dragB={x:canvas.getBoundingClientRect().width-64,y:p.y};e.preventDefault();draw()});
canvas.addEventListener('pointerup',e=>{if(!selecting)return;selecting=false;try{canvas.releasePointerCapture?.(e.pointerId)}catch(_){}e.preventDefault();draw()});
canvas.addEventListener('pointercancel',()=>{selecting=false;draw()});
document.getElementById('clearBtn').onclick=()=>{if(submitted)return;selecting=false;dragA=dragB=null;draw()};
document.getElementById('submitBtn').onclick=()=>{if(!dragA||!dragB){alert('请先在图表上框选价格区域。');return}const b=bounds(),h=canvas.getBoundingClientRect().height,pA=yp(Math.min(dragA.y,dragB.y),b,h),pB=yp(Math.max(dragA.y,dragB.y),b,h),uLow=Math.min(pA,pB),uHigh=Math.max(pA,pB),a=C().answer,inter=Math.max(0,Math.min(uHigh,a.high)-Math.max(uLow,a.low)),union=Math.max(uHigh,a.high)-Math.min(uLow,a.low),iou=union>0?inter/union:0,centerGap=Math.abs((uLow+uHigh)/2-(a.low+a.high)/2),span=Math.max(.01,a.high-a.low),widthRatio=(uHigh-uLow)/span;let score=0,label='需要修正',headline='你的框选没有覆盖主要规则区域';if(iou>=.45){score=100;label='判断正确';headline='外部流动性区域识别正确'}else if(inter>0&&centerGap<=span*1.7){score=60;label='接近';headline='方向接近，但区域范围需要更精确'}submitted=true;state[C().id]={score,userLow:uLow,userHigh:uHigh,answerLow:a.low,answerHigh:a.high,side:C().side,centerGap,widthRatio,when:new Date().toISOString()};saveState();stats();buildList();document.getElementById('grade').textContent=label;document.getElementById('headline').textContent=headline;document.getElementById('processScore').textContent=score+' / 100';document.getElementById('userAnswer').textContent=`${uLow.toFixed(2)} – ${uHigh.toFixed(2)}`;document.getElementById('ruleAnswer').textContent=`${a.low.toFixed(2)} – ${a.high.toFixed(2)}`;document.getElementById('explainText').textContent=C().explanation;document.getElementById('result').classList.remove('hidden');document.getElementById('submitBtn').disabled=true;document.getElementById('revealBtn').disabled=false;document.getElementById('futureControls').classList.remove('hidden');document.getElementById('nextBtn').disabled=false;draw();if(completed().length===CASES.length)setTimeout(showReport,350)};
function setFutureHours(hours){futureHours=hours;revealed=hours>0;document.querySelectorAll('.future-btn').forEach(b=>b.classList.toggle('active',Number(b.dataset.hours)===hours));document.getElementById('cornerText').textContent=revealed?`已展开后续 ${hours} 小时`:'未来行情已隐藏';if(revealed){document.getElementById('outcomeText').textContent=C().outcome;document.getElementById('outcomeBox').classList.remove('hidden');document.getElementById('revealBtn').textContent=hours<24?'继续查看更长后续':'已查看24小时'}draw()}
document.getElementById('revealBtn').onclick=()=>{setFutureHours(futureHours===0?12:24);if(futureHours>=24)document.getElementById('revealBtn').disabled=true};
document.querySelectorAll('.future-btn').forEach(b=>b.onclick=()=>{const h=Number(b.dataset.hours);setFutureHours(h);document.getElementById('revealBtn').disabled=h>=24;document.getElementById('revealBtn').textContent=h>=24?'已查看24小时':'继续查看更长后续'});
document.getElementById('nextBtn').onclick=()=>loadCase((current+1)%CASES.length);
document.querySelectorAll('.tf-tabs button').forEach(b=>b.onclick=()=>{tf=b.dataset.tf;document.querySelectorAll('.tf-tabs button').forEach(x=>x.classList.toggle('active',x===b));selecting=false;if(!submitted)dragA=dragB=null;draw()});
function sideAvg(side){const rows=CASES.filter(c=>c.side===side&&state[c.id]);if(!rows.length)return null;return Math.round(rows.reduce((s,c)=>s+state[c.id].score,0)/rows.length)}
function showReport(){const rows=completed();if(rows.length<5)return;const vals=rows.map(c=>state[c.id].score),avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length),buy=sideAvg('buy'),sell=sideAvg('sell'),exact=vals.filter(x=>x===100).length,near=vals.filter(x=>x===60).length,miss=vals.filter(x=>x===0).length;document.getElementById('reportAvg').textContent=avg;document.getElementById('buyAvg').textContent=buy===null?'—':buy;document.getElementById('sellAvg').textContent=sell===null?'—':sell;document.getElementById('distribution').textContent=`${exact} / ${near} / ${miss}`;let rec='继续提高区域精度：优先复盘低分题，并用新的陌生案例重新测试。';if(buy!==null&&sell!==null&&buy+10<sell)rec='Buy-side 外部流动性明显弱于 Sell-side。下一轮优先训练上方流动性优先级与区域精度。';else if(buy!==null&&sell!==null&&sell+10<buy)rec='Sell-side 外部流动性明显弱于 Buy-side。下一轮优先训练下方流动性优先级与区域精度。';else{const tooWide=rows.filter(c=>(state[c.id].widthRatio||0)>2.2).length;if(tooWide>=Math.max(3,Math.ceil(rows.length*.25)))rec='方向识别较均衡，但你的框选经常过宽。下一轮重点训练“主要流动性区域的精度”，避免把整片价格区都当答案。'}document.getElementById('recommendation').textContent=rec;const weak=[...rows].sort((a,b)=>(state[a.id].score-state[b.id].score)||((state[b.id].centerGap||0)-(state[a.id].centerGap||0))).slice(0,3),box=document.getElementById('weakCases');box.innerHTML='';weak.forEach(c=>{const row=document.createElement('div');row.className='weak-case';row.innerHTML=`<div><b>Scenario #${String(c.id).padStart(2,'0')}</b><span style="display:block;color:#7891ac;font-size:11px;margin-top:3px">${c.sideLabel} · ${state[c.id].score}/100</span></div>`;const btn=document.createElement('button');btn.textContent='重看';btn.onclick=()=>{document.getElementById('report').classList.add('hidden');loadCase(CASES.indexOf(c))};row.appendChild(btn);box.appendChild(row)});document.getElementById('result').classList.add('hidden');document.getElementById('report').classList.remove('hidden');document.getElementById('report').scrollIntoView({behavior:'smooth',block:'start'})}
document.getElementById('reportBtn').onclick=showReport;document.getElementById('closeReport').onclick=()=>{document.getElementById('report').classList.add('hidden');document.getElementById('result').classList.toggle('hidden',!submitted)};
document.getElementById('resetBtn').onclick=()=>{if(confirm('确定清空这台设备上的20题训练记录？')){state={};saveState();stats();buildList();loadCase(0)}};
if(!CASES.length){document.getElementById('question').textContent='训练数据未加载';document.getElementById('submitBtn').disabled=true}else{buildList();stats();loadCase(0)}